apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
  labels:
    app: translation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translation-service
  template:
    metadata:
      labels:
        app: translation-service
    spec:
      containers:
      - name: translation-service
        image: <YOUR_ACR_NAME>.azurecr.io/translation-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: connection-string
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8001"
        - name: LINGUEE_API_URL
          value: "https://linguee-api.fly.dev/api/v2/translations"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  type: ClusterIP
  selector:
    app: translation-service
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004

